environments:
  default:
    values:
      - baseDomain: 
        namespace: 

---

helmDefaults:
  wait: false
  createNamespace: false

releases:
  - name: apache
    chart: oci://registry-1.docker.io/bitnamicharts/apache
    version: 10.9.2
    namespace: {{ .Values.namespace }}
    values:
      - ingress:
          enabled: true
          hostname: {{ .Values.baseDomain }}
          ingressClassName: nginx
      - pdb:
          create: true
    labels:
      app: apache

